<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAll(){
        $qb = $this->createQueryBuilder('task');
        $qb->select('task.title', 'task.description')
            ->join('task.category', 'category')
            ->addSelect('category.name as categ')
            ->join('task.picture', 'picture')
            ->addSelect('picture.name as img');

        return $qb->getQuery()->getResult();
    }
}
